<?php
if (!function_exists('nimmo_font_etline')) :

    add_filter( 'vc_iconpicker-type-etline', 'nimmo_font_etline' );
    /**
    * awesome class.
    * 
    * @return string[]
    * @author CaseThemes
    */
    function nimmo_font_etline( $icons ) {
        $etline = array (
            array( 'et-mobile' => esc_html( 'ET Line' ) ), 
            array( 'et-laptop' => esc_html( 'ET Line' ) ), 
            array( 'et-desktop' => esc_html( 'ET Line' ) ), 
            array( 'et-tablet' => esc_html( 'ET Line' ) ), 
            array( 'et-phone' => esc_html( 'ET Line' ) ), 
            array( 'et-document' => esc_html( 'ET Line' ) ), 
            array( 'et-documents' => esc_html( 'ET Line' ) ), 
            array( 'et-search' => esc_html( 'ET Line' ) ), 
            array( 'et-clipboard' => esc_html( 'ET Line' ) ), 
            array( 'et-newspaper' => esc_html( 'ET Line' ) ), 
            array( 'et-notebook' => esc_html( 'ET Line' ) ), 
            array( 'et-book-open' => esc_html( 'ET Line' ) ), 
            array( 'et-browser' => esc_html( 'ET Line' ) ), 
            array( 'et-calendar' => esc_html( 'ET Line' ) ), 
            array( 'et-presentation' => esc_html( 'ET Line' ) ), 
            array( 'et-picture' => esc_html( 'ET Line' ) ), 
            array( 'et-pictures' => esc_html( 'ET Line' ) ), 
            array( 'et-video' => esc_html( 'ET Line' ) ), 
            array( 'et-camera' => esc_html( 'ET Line' ) ), 
            array( 'et-printer' => esc_html( 'ET Line' ) ), 
            array( 'et-toolbox' => esc_html( 'ET Line' ) ), 
            array( 'et-briefcase' => esc_html( 'ET Line' ) ), 
            array( 'et-wallet' => esc_html( 'ET Line' ) ), 
            array( 'et-gift' => esc_html( 'ET Line' ) ), 
            array( 'et-bargraph' => esc_html( 'ET Line' ) ), 
            array( 'et-grid' => esc_html( 'ET Line' ) ), 
            array( 'et-expand' => esc_html( 'ET Line' ) ), 
            array( 'et-focus' => esc_html( 'ET Line' ) ), 
            array( 'et-edit' => esc_html( 'ET Line' ) ), 
            array( 'et-adjustments' => esc_html( 'ET Line' ) ), 
            array( 'et-ribbon' => esc_html( 'ET Line' ) ), 
            array( 'et-hourglass' => esc_html( 'ET Line' ) ), 
            array( 'et-lock' => esc_html( 'ET Line' ) ), 
            array( 'et-megaphone' => esc_html( 'ET Line' ) ), 
            array( 'et-shield' => esc_html( 'ET Line' ) ), 
            array( 'et-trophy' => esc_html( 'ET Line' ) ), 
            array( 'et-flag' => esc_html( 'ET Line' ) ), 
            array( 'et-map' => esc_html( 'ET Line' ) ), 
            array( 'et-puzzle' => esc_html( 'ET Line' ) ), 
            array( 'et-basket' => esc_html( 'ET Line' ) ), 
            array( 'et-envelope' => esc_html( 'ET Line' ) ), 
            array( 'et-streetsign' => esc_html( 'ET Line' ) ), 
            array( 'et-telescope' => esc_html( 'ET Line' ) ), 
            array( 'et-gears' => esc_html( 'ET Line' ) ), 
            array( 'et-key' => esc_html( 'ET Line' ) ), 
            array( 'et-paperclip' => esc_html( 'ET Line' ) ), 
            array( 'et-attachment' => esc_html( 'ET Line' ) ), 
            array( 'et-pricetags' => esc_html( 'ET Line' ) ), 
            array( 'et-lightbulb' => esc_html( 'ET Line' ) ), 
            array( 'et-layers' => esc_html( 'ET Line' ) ), 
            array( 'et-pencil' => esc_html( 'ET Line' ) ), 
            array( 'et-tools' => esc_html( 'ET Line' ) ), 
            array( 'et-tools-2' => esc_html( 'ET Line' ) ), 
            array( 'et-scissors' => esc_html( 'ET Line' ) ), 
            array( 'et-paintbrush' => esc_html( 'ET Line' ) ), 
            array( 'et-magnifying-glass' => esc_html( 'ET Line' ) ), 
            array( 'et-circle-compass' => esc_html( 'ET Line' ) ), 
            array( 'et-linegraph' => esc_html( 'ET Line' ) ), 
            array( 'et-mic' => esc_html( 'ET Line' ) ), 
            array( 'et-strategy' => esc_html( 'ET Line' ) ), 
            array( 'et-beaker' => esc_html( 'ET Line' ) ), 
            array( 'et-caution' => esc_html( 'ET Line' ) ), 
            array( 'et-recycle' => esc_html( 'ET Line' ) ), 
            array( 'et-anchor' => esc_html( 'ET Line' ) ), 
            array( 'et-profile-male' => esc_html( 'ET Line' ) ), 
            array( 'et-profile-female' => esc_html( 'ET Line' ) ), 
            array( 'et-bike' => esc_html( 'ET Line' ) ), 
            array( 'et-wine' => esc_html( 'ET Line' ) ), 
            array( 'et-hotairballoon' => esc_html( 'ET Line' ) ), 
            array( 'et-globe' => esc_html( 'ET Line' ) ), 
            array( 'et-genius' => esc_html( 'ET Line' ) ), 
            array( 'et-map-pin' => esc_html( 'ET Line' ) ), 
            array( 'et-dial' => esc_html( 'ET Line' ) ), 
            array( 'et-chat' => esc_html( 'ET Line' ) ), 
            array( 'et-heart' => esc_html( 'ET Line' ) ), 
            array( 'et-cloud' => esc_html( 'ET Line' ) ), 
            array( 'et-upload' => esc_html( 'ET Line' ) ), 
            array( 'et-download' => esc_html( 'ET Line' ) ), 
            array( 'et-target' => esc_html( 'ET Line' ) ), 
            array( 'et-hazardous' => esc_html( 'ET Line' ) ),
            array( 'et-piechart' => esc_html( 'ET Line' ) ), 
            array( 'et-speedometer' => esc_html( 'ET Line' ) ), 
            array( 'et-global' => esc_html( 'ET Line' ) ), 
            array( 'et-compass' => esc_html( 'ET Line' ) ), 
            array( 'et-lifesaver' => esc_html( 'ET Line' ) ), 
            array( 'et-clock' => esc_html( 'ET Line' ) ), 
            array( 'et-aperture' => esc_html( 'ET Line' ) ), 
            array( 'et-quote' => esc_html( 'ET Line' ) ), 
            array( 'et-scope' => esc_html( 'ET Line' ) ), 
            array( 'et-alarmclock' => esc_html( 'ET Line' ) ), 
            array( 'et-refresh' => esc_html( 'ET Line' ) ), 
            array( 'et-happy' => esc_html( 'ET Line' ) ), 
            array( 'et-sad' => esc_html( 'ET Line' ) ), 
            array( 'et-facebook' => esc_html( 'ET Line' ) ), 
            array( 'et-twitter' => esc_html( 'ET Line' ) ), 
            array( 'et-googleplus' => esc_html( 'ET Line' ) ), 
            array( 'et-rss' => esc_html( 'ET Line' ) ), 
            array( 'et-tumblr' => esc_html( 'ET Line' ) ), 
            array( 'et-linkedin' => esc_html( 'ET Line' ) ), 
            array( 'et-dribbble' => esc_html( 'ET Line' ) ),
        );
        return array_merge( $icons, $etline );
    }
endif;